// 10 animal reward patterns
export const ANIMALS = [
  {
    id: 0,
    name: 'パンダ',
    hero: '🐼',
    particles: ['🎋', '🎋', '🎋', '🎋', '🌿'],
    heroAnim: 'bounce',
    particleAnim: 'sway',
  },
  {
    id: 1,
    name: 'ネコ',
    hero: '🐱',
    particles: ['⭐', '✨', '💫', '⭐', '✨', '💫'],
    heroAnim: 'spin',
    particleAnim: 'twinkle',
  },
  {
    id: 2,
    name: 'イヌ',
    hero: '🐶',
    particles: ['🦴', '🦴', '🦴', '🦴', '🦴'],
    heroAnim: 'shake',
    particleAnim: 'fall',
  },
  {
    id: 3,
    name: 'ウサギ',
    hero: '🐰',
    particles: ['🥕', '🥕', '🥕', '🌸', '🌸'],
    heroAnim: 'hop',
    particleAnim: 'float',
  },
  {
    id: 4,
    name: 'ペンギン',
    hero: '🐧',
    particles: ['❄️', '❄️', '❄️', '❄️', '❄️', '🌨️'],
    heroAnim: 'waddle',
    particleAnim: 'snow',
  },
  {
    id: 5,
    name: 'カエル',
    hero: '🐸',
    particles: ['💧', '💧', '💧', '🌿', '🌿'],
    heroAnim: 'jump',
    particleAnim: 'drip',
  },
  {
    id: 6,
    name: 'クマ',
    hero: '🐻',
    particles: ['🍯', '🍯', '🍁', '🍂', '🍁'],
    heroAnim: 'pulse',
    particleAnim: 'orbit',
  },
  {
    id: 7,
    name: 'ヒヨコ',
    hero: '🐥',
    particles: ['🌟', '⭐', '💛', '🌟', '⭐', '💛'],
    heroAnim: 'floatUp',
    particleAnim: 'scatter',
  },
  {
    id: 8,
    name: 'キツネ',
    hero: '🦊',
    particles: ['🍂', '🍁', '🍂', '🍁', '🍂'],
    heroAnim: 'cartwheel',
    particleAnim: 'swirl',
  },
  {
    id: 9,
    name: 'ゾウ',
    hero: '🐘',
    particles: ['🌈', '🌊', '💦', '💦', '🌊'],
    heroAnim: 'sway',
    particleAnim: 'rise',
  },
];
